config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'

  resources :sessions, only: [:update]
  resources :projects

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new  #if current_user is nil then set up a new user
    
    if user.role?(:admin)
      can :manage, :all
    elsif user.role?(:user)
      can :read, Project, ongoing:true
    elsif user.role?(:moderator)
      # can :manage, Project
      # cannot :destroy, Project
      can :create, Project
      can :read, Project
      can :update, Project do |p|
        p.ongoing?
      end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User 

  ROLES = { 0 => :guest, 1 => :user, 2 => :moderator, 3 => :admin }

  attr_reader :role

  def initialize(role_id = 0)
    @role = ROLES.has_key?(role_id) ? ROLES[role_id.to_i] : ROLES[0]
  end

  def role?(role_name)
    role == role_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  check_authorization
  protect_from_forgery with: :exception

  private 

  def current_user
    User.new(session[:id])
  end

  helper_method :current_user
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_authorization_check

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :load_projects, only: :index
  load_and_authorize_resource # or load_resource; authorize_resource

  def create
    if @project.save
      flash[:success] = "Project was saved!"
      redirect_to root_path
    else
      render "new"
    end
  end

  def update
    if @project.update_attributes(update_params)
      flash[:success] = "Project was updated"
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = "Project was deleted"
    else
      flash[:error] = "Cannot destroy project"
    end
    redirect_to root_path
  end

  private

  # if If there is no create_params or update_params method defined, 
  # CanCanCan will search for _params method – this is what we are using in our demo (project_params).
  # Lastly, CanCanCan will search for a method with a static name resource_params.
  #
  # def project_params
  #   params.require(:project).permit(:title, :ongoing)
  # end
  #
  def create_params
    params.require(:project).permit(:title, :ongoing)
  end

  def update_params
    params.require(:project).permit(:title, :ongoing)
  end

  def load_projects
    @projects = Project.accessible_by(current_ability).order("created_at DESC")
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_authorization_check

  def update
    id = params[:id].to_i
    session[:id] = User::ROLES.has_key?(id) ? id : 0
    flash[:success] = "Your new role #{User::ROLES[id]} was set"
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ICan</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'iCan', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav pull-right">
        <ul class="nav navbar-nav">
          <% if can? :create, Project %>
            <li><%= link_to 'Add Project', new_project_path %></li>
          <% end %>
        </ul>
        <li class="dropdown">
          <a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="#">
            Role
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% User::ROLES.each do |k, v| %>
              <li>
                <%= link_to session_path(k), method: :patch do %>
                  <%= v %>
                  <% if v == current_user.role %>
                    <small class="text-muted">(current)</small>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
        </ul>
      </div>
    </div>
  </nav>
   
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/index.html.erb
<div class="page_header">
  <h1>Welcome!</h1>

  <% if can? :index, Project %>
    <%= link_to 'Projects', projects_path, class: 'btn btn-lg btn-primary' %>
  <% end %>

</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :ongoing %>
    <%= f.check_box :ongoing %>
  </div>
  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header"><h1>Projects</h1></div>
 
<% @projects.each do |project| %>
  <div class="well well-sm">
    <h2><%= project.title %></h2>
    <% if can? :update, project %>
      <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-info' %>
    <% end %>

    <% if can? :destroy, project %>
      <%= link_to 'Delete', project_path(project), { method: :destroy, class: 'btn btn-danger', data: {confirm: 'Are you sure'} } %>
    <% end %>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>New Project</h1>
</div>

<%=  render 'form' %>